In [1]:
import pandas as pd
import matplotlib.pyplot as mplt
rg = pd.read_csv("Recycling__Garbage_and_Yard_Waste_Collection_Days_20240409.csv")

In [2]:
rg

        Address ID           Combined Address Collection Day
0           192875            758 SELKIRK AVE     THURSDAY A
1           193539           154 SHERBROOK ST       FRIDAY A
2           192852            9 ST JOHN'S AVE     THURSDAY A
3           206297         701 WELLINGTON AVE       FRIDAY A
4           207176        176 THOMAS BERRY ST      TUESDAY A
...            ...                        ...            ...
208953      233928                3 KILROY ST       MONDAY A
208954      241713  302 WASHINGTON AVE UNIT B       FRIDAY A
208955      244811            242 SELKIRK AVE     THURSDAY A
208956      244807                30 AVIOR DR    WEDNESDAY A
208957      152713            855 KILDONAN DR       MONDAY B

[208958 rows x 3 columns]

In [3]:
rg.head

<bound method NDFrame.head of         Address ID           Combined Address Collection Day
0           192875            758 SELKIRK AVE     THURSDAY A
1           193539           154 SHERBROOK ST       FRIDAY A
2           192852            9 ST JOHN'S AVE     THURSDAY A
3           206297         701 WELLINGTON AVE       FRIDAY A
4           207176        176 THOMAS BERRY ST      TUESDAY A
...            ...                        ...            ...
208953      233928                3 KILROY ST       MONDAY A
208954      241713  302 WASHINGTON AVE UNIT B       FRIDAY A
208955      244811            242 SELKIRK AVE     THURSDAY A
208956      244807                30 AVIOR DR    WEDNESDAY A
208957      152713            855 KILDONAN DR       MONDAY B

[208958 rows x 3 columns]>

In [4]:
rg.head()

   Address ID     Combined Address Collection Day
0      192875      758 SELKIRK AVE     THURSDAY A
1      193539     154 SHERBROOK ST       FRIDAY A
2      192852      9 ST JOHN'S AVE     THURSDAY A
3      206297   701 WELLINGTON AVE       FRIDAY A
4      207176  176 THOMAS BERRY ST      TUESDAY A

In [5]:
combined_address = rg["Combined Address"].value_counts()[0:10]

In [6]:
combined_address

Combined Address
1010 SINCLAIR ST         2
60 CHESTERFIELD AVE      2
515 THOMPSON DR          2
54 WEST GATE             2
2850 SASKATCHEWAN AVE    2
793 ARCHIBALD ST         2
71 ST ANNE'S RD          2
569 ST MARY'S RD         2
732 VIMY RD              2
360 STAFFORD ST          2
Name: count, dtype: int64

In [7]:
address_id = rg["Address ID"].value_counts()[0:10]

In [8]:
address_id

Address ID
208095    2
236421    2
207618    2
211405    2
194245    2
206485    2
237087    2
193456    2
207049    2
218092    2
Name: count, dtype: int64

In [9]:
rg

        Address ID           Combined Address Collection Day
0           192875            758 SELKIRK AVE     THURSDAY A
1           193539           154 SHERBROOK ST       FRIDAY A
2           192852            9 ST JOHN'S AVE     THURSDAY A
3           206297         701 WELLINGTON AVE       FRIDAY A
4           207176        176 THOMAS BERRY ST      TUESDAY A
...            ...                        ...            ...
208953      233928                3 KILROY ST       MONDAY A
208954      241713  302 WASHINGTON AVE UNIT B       FRIDAY A
208955      244811            242 SELKIRK AVE     THURSDAY A
208956      244807                30 AVIOR DR    WEDNESDAY A
208957      152713            855 KILDONAN DR       MONDAY B

[208958 rows x 3 columns]

In [10]:
target_value = 'SELKIRK AVE'

counts_dict = {}

for index, row in rg.iterrows():
    column_value = row['Collection Day']
    
    if target_value in str(row.values):
        counts_dict[column_value] = counts_dict.get(column_value, 0) + 1

for value, count in counts_dict.items():
    print("Number of times '{}' appears in the same row with '{}'".format(target_value, value, count))

Number of times 'SELKIRK AVE' appears in the same row with 'THURSDAY A'
Number of times 'SELKIRK AVE' appears in the same row with 'WEDNESDAY B'